/**
 * ResolutionSelector — output-resolution tier for Z-Image / SD3-family gens.
 * The format selector fixes the RATIO; this picks the SIZE. Mirrors the backend
 * app/utils/resolution.py (same ratios / tiers / ÷16 / 1536 cap) so the px shown
 * here match what's generated. The exact matrix is generated by the backend
 * and returned in capabilities; this component contains no dimension table.
 *
 * Props:
 *   value        - 'fast'|'standard'|'hq'|'max'
 *   aspectRatio  - current format key (to display the resulting WxH)
 *   onChange     - (value) => void
 */

import { useCapabilities } from '../../context/CapabilitiesContext';
import { tierDims } from '../../utils/resolutionMetadata';

export default function ResolutionSelector({ value = 'standard', aspectRatio = 'square', onChange, maxLongSide, label = 'Resolution', showDimensions = true }) {
  const { caps } = useCapabilities();
  const metadata = caps.resolution_metadata;
  const tiers = metadata?.tiers || [];
  const moveSelection = (event) => {
    const index = tiers.findIndex((tier) => tier.value === value);
    if (index < 0 || !tiers.length) return;
    let next = index;
    if (['ArrowRight', 'ArrowDown'].includes(event.key)) next = (index + 1) % tiers.length;
    else if (['ArrowLeft', 'ArrowUp'].includes(event.key)) next = (index - 1 + tiers.length) % tiers.length;
    else if (event.key === 'Home') next = 0;
    else if (event.key === 'End') next = tiers.length - 1;
    else return;
    event.preventDefault();
    onChange?.(tiers[next].value);
    event.currentTarget.parentElement?.querySelector(`[data-tier="${tiers[next].value}"]`)?.focus();
  };
  return (
    <div className="grid grid-cols-4 gap-2" role="radiogroup" aria-label={label} onKeyDown={moveSelection}>
      {tiers.map((t) => {
        const selected = value === t.value;
        const [w, h] = tierDims(metadata, aspectRatio, t.value, maxLongSide);
        return (
          <button
            key={t.value}
            type="button"
            role="radio"
            aria-checked={selected}
            tabIndex={selected ? 0 : -1}
            data-tier={t.value}
            onClick={() => onChange?.(t.value)}
            className={`flex flex-col items-center gap-0.5 py-2 px-1.5 rounded-[10px] border cursor-pointer transition-all duration-150
              ${selected
                ? 'border-primary/70 bg-primary/15 text-white'
                : 'border-white/10 bg-white/[0.04] text-content-muted'
              }`}
          >
            <span className="text-[0.6875rem] font-semibold">{t.label}</span>
            {showDimensions && <span className="text-[0.625rem] opacity-60 tabular-nums">{w}×{h}</span>}
          </button>
        );
      })}
    </div>
  );
}
